### ISSUE TITLE
无法在Forge-1.20.1服务器上运行

### ISSUE THREAD

**Issue by FuDujilm** [pltision/toNekoReforged#2]
这里是日志https://mclo.gs/FYSGSaJ

其中关键在于：
[232��2024 00:35:04.651] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
--
11 | Mod ID: 'minecraft', Requested by: 'to_neko', Expected range: '[1.18.x,1.20.x)', Actual version: '1.20.1'
12 | [232��2024 00:35:08.279] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
13 | [232��2024 00:35:08.344] [main/ERROR] [mixin/]: Mixin config yuushya.mixins.json does not specify "minVersion" property
14 | [232��2024 00:35:08.409] [main/ERROR] [mixin/]: Mixin config mixins.baritone.json does not specify "minVersion" property

**Comment by pltision** [comment]
这是由于我的versionRange填写错误导致的喵，它之所以只炸服务端是因为写了side="SERVER"。抱歉我没有在服务端测试过，bug已在0.2.1版本中修复。

**Comment by FuDujilm** [comment]
thank a lot
